name: "CI Ubuntu Init"
description: "Set up variables and install dependencies for ci-ubuntu"

runs:
  using: "composite"
  ########################################################################
  ## INITIALISATION
  ########################################################################
  steps:

    - name: Initialise variables
      run: |
        if [[ '${{ github.ref }}' == 'refs/heads/experimental' \
            || '${{ github.base_ref }}' == 'experimental' ]]; then
          # Pick Agda version for experimental
          echo "AGDA_COMMIT=tags/v2.8.0" >> "${GITHUB_ENV}";
          echo "AGDA_HTML_DIR=html/experimental" >> "${GITHUB_ENV}"
        else
          # Pick Agda version for master
          echo "AGDA_COMMIT=tags/v2.8.0" >> "${GITHUB_ENV}";
          echo "AGDA_HTML_DIR=html/master" >> "${GITHUB_ENV}"
        fi

        if [[ '${{ github.ref }}' == 'refs/heads/master' \
            || '${{ github.ref }}' == 'refs/heads/experimental' ]]; then
            echo "AGDA_DEPLOY=true" >> "${GITHUB_ENV}"
        fi

    ########################################################################
    ## CACHING
    ########################################################################


    # This caching step allows us to save a lot of building time by only
    # downloading ghc and cabal and rebuilding Agda if absolutely necessary
    # i.e. if we change either the version of Agda, ghc, or cabal that we want
    # to use for the build.
    - name: Cache ~/.cabal directories
      uses: actions/cache@v4
      id: cache-cabal
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          ~/.cabal/bin
          ~/.cabal/share
        key: ${{ runner.os }}-${{ env.GHC_VERSION }}-${{ env.CABAL_VERSION }}-${{ env.AGDA_COMMIT }}-cache

    ########################################################################
    ## INSTALLATION STEPS
    ########################################################################

    - name: Install ghc & cabal
      uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ env.GHC_VERSION }}
        cabal-version: ${{ env.CABAL_VERSION }}
        cabal-update: true

    - name: Put cabal programs in PATH
      run: echo ~/.cabal/bin >> "${GITHUB_PATH}"

    - name: Install alex & happy
      if: steps.cache-cabal.outputs.cache-hit != 'true'
      run: |
        ${{ env.CABAL_INSTALL }} alex
        ${{ env.CABAL_INSTALL }} happy
        # happy>=2.0 cannot be v1-installed: https://github.com/haskell/happy/issues/315
        # Since we only need the executable, it is fine to use v2-install here.

    - name: Download and install Agda from github
      if: steps.cache-cabal.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/agda/agda
        cd agda
        git checkout ${{ env.AGDA_COMMIT }}
        mkdir -p doc
        touch doc/user-manual.pdf
        ${{ env.CABAL_V1_INSTALL }}
        cd ..

    # By default github actions does not pull the repo
    - name: Checkout stdlib
      uses: actions/checkout@v5