name: Ubuntu build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GHC_VERSION: 8.6.5
  CABAL_VERSION: 3.2.0.0
  AGDA_COMMIT: tags/v2.6.1.3
  GHC_OPTIONS: '-O2 +RTS -M6G -RTS'
  CABAL_OPTIONS: --overwrite-policy=always --ghc-options=${{ GHC_OPTIONS }}
  CABAL_INSTALL: cabal install ${{ CABAL_OPTIONS }}

jobs:
  test-stdlib:
    runs-on: ubuntu-latest
    steps:
      - name: Cache cabal packages
        uses: actions/cache@v2
        id: cache-cabal
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            ~/.cabal/bin
            dist-newstyle
           key: ${{ runner.os }}-${{ GHC_VERSION }}-${{ CABAL_VERSION }}-${{ AGDA_COMMIT }}

      - name: Install cabal
        if: steps.cache-cabal.outputs.cache-hit != 'true'
        uses: actions/setup-haskell@v1.1.3
        with:
          ghc-version: ${{ GHC_VERSION }}
          cabal-version: ${{ CABAL_VERSION }}

      - name: Put cabal programs in PATH
        run: echo "~/.cabal/bin" >> $GITHUB_PATH

      - name: Download Agda from github
        if: steps.cache-cabal.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: agda/agda
          path: agda
          ref: ${{ AGDA_COMMIT }}

      - name: Install Agda
        if: steps.cache-cabal.outputs.cache-hit != 'true'
        run: |
          cabal update
          ${{ CABAL_INSTALL }} alex-3.2.5
          ${{ CABAL_INSTALL }} happy-1.19.12
          cd agda
        mkdir -p doc
        touch doc/user-manual.pdf
        ${{ CABAL_INSTALL }}

     # Download and test stdlib
      - name: Checkout stdlib
        uses: actions/checkout@v2

      - name: Test stdlib
        run: |
          cabal install agda-stdlib-utils.cabal
          runghc GenerateEverything.hs

      - name: Deploy html to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html/
