name: Check whitespace
on:
  push:
    branches:
      - master
      - experimental
  pull_request:
    branches:
      - master
      - experimental
  merge_group:

jobs:
  check-whitespace:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: andreasabel/fix-whitespace-action@v1
